### ISSUE TITLE
Classes must be in toplevel scope.

### ISSUE THREAD

**Issue by yxhuvud** [drujensen/kemalyst-model#23]
The macros break when trying to put the model inside a module, eg 

```
  module Foo
    class Wat < Kemalyst::Model
      adapter pg
      sql_mapping({unicorns: String})
    end
  end
```

**Comment by drujensen** [comment]
@yxhuvud thanks for reporting this.  I will look into it soon.

**Comment by drujensen** [comment]
@yxhuvud Do you think you would have some time to look into this issue and possibly contribute a fix?

The table name should probably include the module so for your example the table name would be `foo_wat`.  I think this is the way rails does it.

**Comment by drujensen** [comment]
@yxhuvud I found an easy fix and will deploy soon..

**Comment by drujensen** [comment]
Release v0.5.5 fixes this issue.
