### ISSUE TITLE
Support id columns of type Int32 for legacy tables

### ISSUE THREAD

**Issue by lhz** [drujensen/kemalyst-model#27]
It would be neat to be able to override the type of the `id` column when defining a model class.

Use case: I have an existing Rails app using MySQL as database backend, and want to implement a new microservice in Crystal operating on the same database. The `id` column in this database is of type `INT(11)`, which maps to an `Int32` with the mysql adapter.

This currently precludes the use of `kemalyst-model` as a mapping layer due to its hardcoded type of Int64 type `id` columns.

**Comment by drujensen** [comment]
Thanks for the feature request. 

With the recent changes to support finished macro, we should be able to add a primary key macro with overrides. 

Is this something you would be interested in working on?

If not, I will take a stab at it.

**Comment by drujensen** [comment]
I see you forked the repo. Let me know if you need any help on this.

what do you think of:
```crystal
primary id : Int32
```
as the macro name?

Then maybe maintain a separate hash for the primary.   In the finished macro you can replace the hard-coded id.  You might need to update all the adapters as well.

**Comment by drujensen** [comment]
This will allow us to rename the primary key as well which should help with backward compatibility to legacy db's.

**Comment by lhz** [comment]
I'll see if I can come up with something and get back to you with a PR, or some questions. Your idea of a primary macro for custom column and type looks good!

**Comment by lhz** [comment]
Looks like the `#save`, `#destroy`, `.all`, `.find` and `find_by` methods will also need to be generated inside macros for this to work.

**Comment by lhz** [comment]
To use a customized primary column type it looks like I'll need to make most of the instance method definitions on the model take place inside macros as well.

**Comment by lhz** [comment]
As far as I can tell, the most straightforward solution is to add an extra `primary_name` parameter to the adapters' `update` and `delete` methods. The return type and casting in the adapters' `insert` method can be dropped, then do the casting inside the model where the value is returned instead.

**Comment by drujensen** [comment]
Yes, sounds right.
