### ISSUE TITLE
Weird issue when I try to use kemalyst model without kemalyst.

### ISSUE THREAD

**Issue by elorest** [drujensen/kemalyst-model#35]
I copied a model that worked perfectly within a kemalyst project over to a simpler kemal project but I get a confusing error when I try to compile. I've included kemalyst-model and crystal-mysql. But for some reason I get this error.

```
 138.     def self.all(clause = "", params = [] of DB::Any)
 139.       rows = [] of self
>140.       @@adapter.select(@@table_name, fields([@@primary_name]), clause, params) do |results|
 141.         results.each do
 142.           rows << self.from_sql(results)
 143.         end
 144.       end
 145.       return rows
 146.     end

instantiating 'Kemalyst::Adapter::Mysql#select(String, Array(String), String, Array(Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil))'
in lib/kemalyst-model/src/adapter/mysql.cr:61: instantiating 'open()'
```

Is there some other dependency I'm unaware of?

**Comment by drujensen** [comment]
no other dependency.  the mysql.cr open() is when it connects to the db.  Can you confirm the config/database.yml or DATABASE_URL is correct?

**Comment by drujensen** [comment]
Looking at the code, it may require the `config/database.yml` file to exist.

**Comment by elorest** [comment]
I should have mentioned that it does exist. I copied that over as well.

**Comment by elorest** [comment]
I just tried it in the amber framework too. I don't get what's different. I copied the exact same model and database.yml over and added kemalyst-model and crystal-mysql to the shard.yml.

**Comment by elorest** [comment]
I just verified that the version numbers for the shards were the same as well.

**Comment by elorest** [comment]
```
in /Users/isaac/.anyenv/envs/crenv/versions/0.21.1/src/hash.cr:336: instantiating 'each()'

    each do |key, value|
    ^~~~

in /Users/isaac/.anyenv/envs/crenv/versions/0.21.1/src/set.cr:149: instantiating 'Hash(WeakRef(DB::Connection), Nil)#each_key()'

    @hash.each_key do |key|
          ^~~~~~~~

in lib/db/src/db/pool_prepared_statement.cr:42: instantiating 'Set(WeakRef(DB::Connection))#each()'

      @connections.each do |ref|
                   ^~~~

in lib/db/src/db/pool_prepared_statement.cr:43: undefined method 'value' for WeakRef(DB::Connection)

        conn = ref.value
                   ^~~~~
```

That's the end of the error message. If it helps at all.

**Comment by drujensen** [comment]
crystal version is 0.22.0.  This is a breaking change in 0.21.1.

**Comment by elorest** [comment]
So dumb of me. Thank you.

**Comment by drujensen** [comment]
No worries.  I ran into this same issue a week ago otherwise I would have been lost.  Looking forward to semantic versioning in some of these projects.

I should probably check if `config/database.yml`  exists and ignore if it doesn't.

**Comment by elorest** [comment]
Yeah. Unless it crashes if yaml can't read it the envvar overrides it
anyway.

**Comment by elorest** [comment]
https://github.com/drujensen/kemalyst-model/blob/master/src/kemalyst-model.cr#L25

At that point it loads: `database: mysql://root@localhost:3306/test_blog_development`
DATABASE_URL just equals. "mysql://root@localhost:3306/test_blog_development`
