### ISSUE TITLE
Integer fields ?

### ISSUE THREAD

**Issue by m4tm4t** [drujensen/kemalyst-model#7]
Hi,

I'm trying to setup INTEGER field in sql_mapping, but look like buggy.

``` crystal
class Board < Kemalyst::Model
  adapter sqlite

  sql_mapping({
    user_id: ["INTEGER", Int32]
  })

end

b = Board.new
b.user_id = 42
b.save
```

When saving, I'm getting :

```
Error in ./app/models/board.cr:14: instantiating 'Board#save()'

b.save
  ^~~~


in ./libs/kemalyst-model/kemalyst-model.cr:173: instantiating 'Kemalyst::Adapter::Sqlite#update(String, Hash(String, String), (Int32 | Int64), Hash(String, Int32 | Time | Nil))'

          db.update(@@table_name, self.class.fields, value, params)
             ^~~~~~

in ./libs/kemalyst-model/adapter/sqlite.cr:110: no overload matches 'Hash(String, Int32 | Time | Nil)#[]=' with types String, String
Overloads are:
 - Hash(K, V)#[]=(key : K, value : V)

      params["id"] = "#{id}"
```

I looked into spec and I feel surprised that there isn't any integer field covered :octocat:

**Comment by drujensen** [comment]
Hi,

There is a known issue related to the SQLite adapter. The driver was rewritten and built using its own adapter pattern which will be difficult/ugly if I integrate as is. 

Regarding specs per type, it could definitely use more specs. Any help is appreciated. 

Dru

**Comment by foohey** [comment]
In fact the sqlite3 adapter work very well if I use the driver from old repo
```yaml
  sqlite3:
    github: manastech/crystal-sqlite3
    commit: 135f33d9eac82c63a48b14942c8eff647c070410
```
I found that the error happen if there's no `["VARCHAR(255)", String]` defined in `sql_mapping`

**Comment by drujensen** [comment]
That is very useful information.  I didn’t realize that repository was still available.

Regarding the type cast error, I never tested without a string so I will look into adding that test scenario.

Thanks!

**Comment by foohey** [comment]
I ran another issue when fetching existing rows : 
```
          model.user_id = String.new ( result[1] as Slice(UInt8) )
                ^~~~~~~

no overload matches 'Board#user_id=' with type String
Overloads are:
 - Board#user_id=(user_id : Int32 | ::Nil)
```
that come from the `from_sql` method. After looking at the source, I don't understand the use case of the condition at line #60
```crystal
        if result[{{i}}].class == Slice(UInt8) && {{types[1].id}} == String
          model.{{name.id}} = String.new ( result[{{i}}] as Slice(UInt8) )
        else
          model.{{name.id}} = result[{{i}}] as? {{types[1].id}}
        end
```
After some debug, the `result[{{i}}].class` and `{{types[1].id}}` for the `user_id` field are `Int32`

So it should look like `Int32 == Slice(UInt8) && Int32 == String` and should return false, very strange condition result

For now I let `model.{{name.id}} = result[{{i}}] as? {{types[1].id}}` alone and seems to work but maybe you encountered other cases?

**Comment by drujensen** [comment]
Very strange.

When I first wrote this using earlier versions of Crystal, it handled the type conversion automatically using Union types, so the mapping was simple.

To support later versions, I had to explicitly add the type to the sql_mapping, but as you can see, that didn’t work for the SQLLite driver and String.

I think this is kludgy.  It could use some refactoring and a better design for handling types.

**Comment by foohey** [comment]
I just tested with postgres and the same behavior occurs

**Comment by yjukaku** [comment]
This also happens with the MySQL adapter.

The sql_mapping in company.cr
```crystal
  sql_mapping({ 
    name: ["VARCHAR(256) NOT NULL", String],
    budget_cents: ["INTEGER NOT NULL", Int32],
  })
```

```
# Error when compiling:

no overload matches 'Company#budget_cents=' with type String
Overloads are:
 - Company#budget_cents=(budget_cents : Int32 | ::Nil)
```

```crystal
# in macro 'sql_mapping' .../libs/kemalyst-model/kemalyst-model.cr:34, line 37:

   1.     
   2.     
   3.     # Table Name
   4.     @@table_name = "companys"
   5.     #Create the properties
   6.     property id : (Int32 | Int64 | Nil)
   7.     
   8.       property name : String?
   9.     
  10.       property budget_cents : Int32?
  11.     
  12.     
  13.     property created_at : Time?
  14.     property updated_at : Time?
  15.     
  16. 
  17.     # Create the from_sql method
  18.     def self.from_sql(result)
  19.       model = Company.new
  20. 
  21.       # hack around different types for Pg and Mysql drivers
  22.       unless model.id = result[0].as?(Int32)
  23.         model.id = result[0].as?(Int64)
  24.       end
  25.       
  26.       
  27.         # Need to find a way to map to other types based on SQL type
  28.         if result[1].class == Slice(UInt8) && String == String
  29.           model.name = String.new ( result[1].as(Slice(UInt8)) )
  30.         else
  31.           model.name = result[1].as?(String)
  32.         end
  33.         
  34.       
  35.         # Need to find a way to map to other types based on SQL type
  36.         if result[2].class == Slice(UInt8) && Int32 == String
> 37.           model.budget_cents = String.new ( result[2].as(Slice(UInt8)) )
  38.         else
  39.           model.budget_cents = result[2].as?(Int32)
  40.         end
  41.         
```

**Comment by drujensen** [comment]
Release 0.2.0 with new Crystal DB Drivers.

**Comment by yjukaku** [comment]
Thanks! 👍 😄
